# Generated by Django 2.0.7 on 2018-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data',
            new_name='date_finish',
        ),
        migrations.AddField(
            model_name='task',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
