# Generated by Django 2.0.7 on 2018-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20180801_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(),
        ),
    ]
